#!/usr/bin/env python3
"""
MetroGIS V6.7 directory cleanup helper.

Safe policy:
- NEVER deletes files.
- Uses move/rename only.
- Does NOT touch core source under metrogis/.
- Keeps the currently active root route_builder_V6_7.py in place for now,
  because the V6.7 development workflow still uses it directly.
- Moves historical V6.7 snapshots, migration scripts, manual integration tests,
  and generated .bak files into organized folders.
- Run without --apply for a dry run.
"""

from __future__ import annotations

import argparse
import shutil
from pathlib import Path


ROOT = Path.cwd()

DIRS = {
    "versions": ROOT / "dev" / "v6.7" / "versions",
    "tools": ROOT / "dev" / "v6.7" / "tools",
    "manual_tests": ROOT / "dev" / "v6.7" / "manual_tests",
    "backups": ROOT / "archive" / "backups",
}


def unique_destination(path: Path) -> Path:
    """Avoid overwriting an existing file."""
    if not path.exists():
        return path

    stem = path.stem
    suffix = path.suffix
    parent = path.parent
    index = 1

    while True:
        candidate = parent / f"{stem}.moved{index}{suffix}"
        if not candidate.exists():
            return candidate
        index += 1


def add_if_exists(bucket: list[tuple[Path, Path]], name: str, target_dir: Path) -> None:
    src = ROOT / name
    if src.exists() and src.is_file():
        bucket.append((src, target_dir / src.name))


def collect_moves() -> list[tuple[Path, Path]]:
    moves: list[tuple[Path, Path]] = []

    # Historical version snapshots.
    for name in (
        "route_builder_V6_7_1_1.py",
        "route_builder_V6_7_2.py",
        "route_builder_V6_7_2_1.py",
    ):
        add_if_exists(moves, name, DIRS["versions"])

    # Migration / install helpers created during V6.7 development.
    for path in sorted(ROOT.glob("apply_v6_*.py")):
        if path.is_file():
            moves.append((path, DIRS["tools"] / path.name))

    # Manual / integration test scripts kept at repo root during development.
    manual_patterns = (
        "test_guangzhou_line3_v6_7*.py",
        "test_relation_identity_selection_v6_7*.py",
        "test_route_master_quality_v6_7*.py",
        "test_route_master_resolution_v6_7*.py",
    )
    seen: set[Path] = set()
    for pattern in manual_patterns:
        for path in sorted(ROOT.glob(pattern)):
            if path.is_file() and path not in seen:
                seen.add(path)
                moves.append((path, DIRS["manual_tests"] / path.name))

    # Versioned backups generated by installers.
    for path in sorted(ROOT.glob("route_builder_*.bak")):
        if path.is_file():
            moves.append((path, DIRS["backups"] / path.name))

    for path in sorted(ROOT.glob("*.py.v6_*")):
        if path.is_file():
            moves.append((path, DIRS["backups"] / path.name))

    # Explicit current V6.7 root snapshot is intentionally NOT moved yet.
    # It remains the active development reference:
    #   ROOT / "route_builder_V6_7.py"

    return moves


def print_plan(moves: list[tuple[Path, Path]]) -> None:
    print()
    print("=" * 78)
    print("MetroGIS V6.7 directory cleanup plan")
    print("=" * 78)

    if not moves:
        print("没有发现需要整理的文件。")
        return

    groups: dict[Path, list[tuple[Path, Path]]] = {}
    for src, dst in moves:
        groups.setdefault(dst.parent, []).append((src, dst))

    for directory, items in groups.items():
        print(f"\n[{directory.relative_to(ROOT)}]")
        for src, dst in items:
            print(f"  {src.name}  ->  {dst.relative_to(ROOT)}")

    print()
    print(f"共 {len(moves)} 个文件将被移动。")


def apply_moves(moves: list[tuple[Path, Path]]) -> None:
    for src, raw_dst in moves:
        raw_dst.parent.mkdir(parents=True, exist_ok=True)
        dst = unique_destination(raw_dst)

        print(f"MOVE  {src.relative_to(ROOT)}")
        print(f"   -> {dst.relative_to(ROOT)}")

        shutil.move(str(src), str(dst))

    # Keep empty organization directories clean.
    for directory in sorted(DIRS.values()):
        directory.mkdir(parents=True, exist_ok=True)

    print()
    print("=" * 78)
    print("目录整理完成。")
    print("=" * 78)
    print()
    print("保留在项目根目录的核心结构：")
    print("  metrogis/")
    print("  tests/")
    print("  README.md")
    print("  CHANGELOG.md")
    print("  pyproject.toml")
    print("  requirements.txt")
    print("  route_builder_V6_7.py   # 当前 V6.7 开发参考，暂不移动")
    print()
    print("V6.7 历史文件：")
    print("  dev/v6.7/versions/")
    print("  dev/v6.7/tools/")
    print("  dev/v6.7/manual_tests/")
    print("  archive/backups/")


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Safely organize MetroGIS V6.7 development artifacts."
    )
    parser.add_argument(
        "--apply",
        action="store_true",
        help="Actually move files. Without this flag the command is dry-run only.",
    )
    args = parser.parse_args()

    if ROOT.name != "MetroGIS":
        print(f"警告：当前目录是 {ROOT}, 不是典型的 /workspaces/MetroGIS。")
        print("请先 cd /workspaces/MetroGIS 再执行。")
        return 2

    moves = collect_moves()
    print_plan(moves)

    if not moves:
        return 0

    if not args.apply:
        print()
        print("当前为 DRY-RUN，没有修改任何文件。")
        print("确认计划无误后执行：")
        print("  python cleanup_metrogis_v67.py --apply")
        return 0

    print()
    print("开始执行移动……")
    apply_moves(moves)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
